sssd: fix shipping python script and modules
The project installs the python script sss_obfuscate to the /usr/sbin
directory and the modules to the /usr/lib/python3.X directory.

The recipe does not ship the python modules to the package sssd, and
thus, it raises the QA issue attached below.

This adds the python artifacts (sss_obfuscate script and module files)
to the dedicated package sssd-python.

Fixes:

	NOTE: Executing Tasks
	ERROR: sssd-2.9.2-r0 do_package: QA Issue: sssd: Files/directories were installed but not shipped in any package:
	  /usr/lib/python3.12/site-packages/pysss.so
	  /usr/lib/python3.12/site-packages/pyhbac.so
	  /usr/lib/python3.12/site-packages/pysss_murmur.so
	  /usr/lib/python3.12/site-packages/pysss_nss_idmap.so
	  /usr/lib/python3.12/site-packages/SSSDConfig
	  /usr/lib/python3.12/site-packages/SSSDConfig-2.9.2-py3.12.egg-info
	  /usr/lib/python3.12/site-packages/SSSDConfig/__init__.py
	  /usr/lib/python3.12/site-packages/SSSDConfig/ipachangeconf.py
	  /usr/lib/python3.12/site-packages/SSSDConfig/sssdoptions.py
	  /usr/lib/python3.12/site-packages/SSSDConfig/__pycache__
	  /usr/lib/python3.12/site-packages/SSSDConfig/__pycache__/__init__.cpython-312.pyc
	  /usr/lib/python3.12/site-packages/SSSDConfig/__pycache__/ipachangeconf.cpython-312.pyc
	  /usr/lib/python3.12/site-packages/SSSDConfig/__pycache__/sssdoptions.cpython-312.pyc
	  /usr/lib/python3.12/site-packages/SSSDConfig-2.9.2-py3.12.egg-info/dependency_links.txt
	  /usr/lib/python3.12/site-packages/SSSDConfig-2.9.2-py3.12.egg-info/top_level.txt
	  /usr/lib/python3.12/site-packages/SSSDConfig-2.9.2-py3.12.egg-info/SOURCES.txt
	  /usr/lib/python3.12/site-packages/SSSDConfig-2.9.2-py3.12.egg-info/PKG-INFO
	Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
	sssd: 17 installed and not shipped files. [installed-vs-shipped]
	ERROR: sssd-2.9.2-r0 do_package: Fatal QA errors were found, failing task.

Signed-off-by: Gaël PORTAY <gael.portay+rtone@gmail.com>