oops: Revert "fixup! sssd: fix shipping python script and modules"
This reverts commit 63515e40da0928ba6d676837c983d8d3ce041185.

NOTE: Executing Tasks
ERROR: sssd-2.9.2-r0 do_package: QA Issue: sssd: Files/directories were installed but not shipped in any package:
  /sssd
  /sssd/__init__.py
  /sssd/source_files.py
  /sssd/source_journald.py
  /sssd/source_reader.py
  /sssd/parser.py
  /sssd/sss_analyze.py
  /sssd/util.py
  /sssd/modules
  /sssd/modules/__init__.py
  /sssd/modules/request.py
  /sssd/modules/error.py
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
sssd: 12 installed and not shipped files. [installed-vs-shipped]
ERROR: sssd-2.9.2-r0 do_package: Fatal QA errors were found, failing task.